/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

const documents = {
    "\n  query GetJourney($id: ID!) {\n    journey(id: $id, idType: slug) {\n      ...JourneyFields\n    }\n  }\n": types.GetJourneyDocument,
    "\n  query GetJourneySlugs {\n    journeys {\n      slug\n    }\n  }\n": types.GetJourneySlugsDocument,
    "\n      query GetJourneys {\n        journeys(where: { featured: true }) {\n          id\n          title\n          slug\n        }\n      }\n    ": types.GetJourneysDocument,
    "\n  mutation JourneyViewEventCreate($input: JourneyViewEventCreateInput!) {\n    journeyViewEventCreate(input: $input) {\n      id\n    }\n  }\n": types.JourneyViewEventCreateDocument,
    "\n  mutation ButtonClickEventCreate($input: ButtonClickEventCreateInput!) {\n    buttonClickEventCreate(input: $input) {\n      id\n    }\n  }\n": types.ButtonClickEventCreateDocument,
    "\n  mutation ChatOpenEventCreate($input: ChatOpenEventCreateInput!) {\n    chatOpenEventCreate(input: $input) {\n      id\n    }\n  }\n": types.ChatOpenEventCreateDocument,
    "\n  \n  fragment ButtonFields on ButtonBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    buttonVariant: variant\n    buttonColor: color\n    size\n    startIconId\n    endIconId\n    action {\n      ...ActionFields\n    }\n  }\n": types.ButtonFieldsFragmentDoc,
    "\n  fragment CardFields on CardBlock {\n    id\n    parentBlockId\n    parentOrder\n    backgroundColor\n    coverBlockId\n    themeMode\n    themeName\n    fullscreen\n  }\n": types.CardFieldsFragmentDoc,
    "\n  fragment GridContainerFields on GridContainerBlock {\n    id\n    parentBlockId\n    parentOrder\n    spacing\n    direction\n    justifyContent\n    alignItems\n  }\n": types.GridContainerFieldsFragmentDoc,
    "\n  fragment GridItemFields on GridItemBlock {\n    id\n    parentBlockId\n    parentOrder\n    xl\n    lg\n    sm\n  }\n": types.GridItemFieldsFragmentDoc,
    "\n  fragment IconFields on IconBlock {\n    id\n    parentBlockId\n    parentOrder\n    iconName: name\n    iconSize: size\n    iconColor: color\n  }\n": types.IconFieldsFragmentDoc,
    "\n  fragment ImageFields on ImageBlock {\n    id\n    parentBlockId\n    parentOrder\n    src\n    alt\n    width\n    height\n    blurhash\n  }\n": types.ImageFieldsFragmentDoc,
    "\n  \n  fragment RadioOptionFields on RadioOptionBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    action {\n      ...ActionFields\n    }\n  }\n": types.RadioOptionFieldsFragmentDoc,
    "\n  mutation RadioQuestionSubmissionEventCreate(\n    $input: RadioQuestionSubmissionEventCreateInput!\n  ) {\n    radioQuestionSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n": types.RadioQuestionSubmissionEventCreateDocument,
    "\n  fragment RadioQuestionFields on RadioQuestionBlock {\n    id\n    parentBlockId\n    parentOrder\n  }\n": types.RadioQuestionFieldsFragmentDoc,
    "\n  mutation SignUpSubmissionEventCreate(\n    $input: SignUpSubmissionEventCreateInput!\n  ) {\n    signUpSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n": types.SignUpSubmissionEventCreateDocument,
    "\n  \n  fragment SignUpFields on SignUpBlock {\n    id\n    parentBlockId\n    parentOrder\n    submitLabel\n    submitIconId\n    action {\n      ...ActionFields\n    }\n  }\n": types.SignUpFieldsFragmentDoc,
    "\n  mutation StepViewEventCreate($input: StepViewEventCreateInput!) {\n    stepViewEventCreate(input: $input) {\n      id\n    }\n  }\n": types.StepViewEventCreateDocument,
    "\n  fragment StepFields on StepBlock {\n    id\n    parentBlockId\n    parentOrder\n    locked\n    nextBlockId\n  }\n": types.StepFieldsFragmentDoc,
    "\n  mutation TextResponseSubmissionEventCreate(\n    $input: TextResponseSubmissionEventCreateInput!\n  ) {\n    textResponseSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n": types.TextResponseSubmissionEventCreateDocument,
    "\n  \n  fragment TextResponseFields on TextResponseBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    hint\n    minRows\n    submitLabel\n    submitIconId\n    action {\n      ...ActionFields\n    }\n  }\n": types.TextResponseFieldsFragmentDoc,
    "\n  fragment TypographyFields on TypographyBlock {\n    id\n    parentBlockId\n    parentOrder\n    align\n    color\n    content\n    variant\n  }\n": types.TypographyFieldsFragmentDoc,
    "\n  \n  fragment VideoFields on VideoBlock {\n    id\n    parentBlockId\n    parentOrder\n    muted\n    autoplay\n    startAt\n    endAt\n    posterBlockId\n    fullsize\n    videoId\n    videoVariantLanguageId\n    source\n    title\n    description\n    image\n    duration\n    video {\n      id\n      title(primary: true) {\n        value\n      }\n      image\n      variant {\n        id\n        hls\n      }\n    }\n    action {\n      ...ActionFields\n    }\n  }\n": types.VideoFieldsFragmentDoc,
    "\n  mutation VideoStartEventCreate($input: VideoStartEventCreateInput!) {\n    videoStartEventCreate(input: $input) {\n      id\n    }\n  }\n": types.VideoStartEventCreateDocument,
    "\n  mutation VideoPlayEventCreate($input: VideoPlayEventCreateInput!) {\n    videoPlayEventCreate(input: $input) {\n      id\n    }\n  }\n": types.VideoPlayEventCreateDocument,
    "\n  mutation VideoPauseEventCreate($input: VideoPauseEventCreateInput!) {\n    videoPauseEventCreate(input: $input) {\n      id\n    }\n  }\n": types.VideoPauseEventCreateDocument,
    "\n  mutation VideoCompleteEventCreate($input: VideoCompleteEventCreateInput!) {\n    videoCompleteEventCreate(input: $input) {\n      id\n    }\n  }\n": types.VideoCompleteEventCreateDocument,
    "\n  mutation VideoExpandEventCreate($input: VideoExpandEventCreateInput!) {\n    videoExpandEventCreate(input: $input) {\n      id\n    }\n  }\n": types.VideoExpandEventCreateDocument,
    "\n  mutation VideoCollapseEventCreate($input: VideoCollapseEventCreateInput!) {\n    videoCollapseEventCreate(input: $input) {\n      id\n    }\n  }\n": types.VideoCollapseEventCreateDocument,
    "\n  mutation VideoProgressEventCreate($input: VideoProgressEventCreateInput!) {\n    videoProgressEventCreate(input: $input) {\n      id\n    }\n  }\n": types.VideoProgressEventCreateDocument,
    "\n  \n  fragment VideoTriggerFields on VideoTriggerBlock {\n    id\n    parentBlockId\n    triggerStart\n    triggerAction: action {\n      ...ActionFields\n    }\n  }\n": types.VideoTriggerFieldsFragmentDoc,
    "\n  \n  \n  fragment JourneyFields on Journey {\n    id\n    slug\n    title\n    description\n    status\n    language {\n      id\n      bcp47\n      iso3\n      name {\n        value\n        primary\n      }\n    }\n    createdAt\n    publishedAt\n    themeName\n    themeMode\n    seoTitle\n    seoDescription\n    template\n    blocks {\n      ...BlockFields\n    }\n    primaryImageBlock {\n      ...ImageFields\n    }\n    userJourneys {\n      id\n      role\n      user {\n        id\n        firstName\n        lastName\n        imageUrl\n      }\n    }\n  }\n": types.JourneyFieldsFragmentDoc,
    "\n  fragment ActionFields on Action {\n    parentBlockId\n    gtmEventName\n    ... on NavigateToBlockAction {\n      blockId\n    }\n    ... on NavigateToJourneyAction {\n      journey {\n        id\n        slug\n        language {\n          bcp47\n        }\n      }\n    }\n    ... on LinkAction {\n      url\n    }\n  }\n": types.ActionFieldsFragmentDoc,
    "\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  fragment BlockFields on Block {\n    id\n    parentBlockId\n    parentOrder\n    ... on ButtonBlock {\n      ...ButtonFields\n    }\n    ... on CardBlock {\n      ...CardFields\n    }\n    ... on GridContainerBlock {\n      ...GridContainerFields\n    }\n    ... on GridItemBlock {\n      ...GridItemFields\n    }\n    ... on IconBlock {\n      ...IconFields\n    }\n    ... on ImageBlock {\n      ...ImageFields\n    }\n    ... on RadioOptionBlock {\n      ...RadioOptionFields\n    }\n    ... on RadioQuestionBlock {\n      ...RadioQuestionFields\n    }\n    ... on SignUpBlock {\n      ...SignUpFields\n    }\n    ... on StepBlock {\n      ...StepFields\n    }\n    ... on TextResponseBlock {\n      ...TextResponseFields\n    }\n    ... on TypographyBlock {\n      ...TypographyFields\n    }\n    ... on VideoBlock {\n      ...VideoFields\n    }\n    ... on VideoTriggerBlock {\n      ...VideoTriggerFields\n    }\n  }\n": types.BlockFieldsFragmentDoc,
};

export function graphql(source: "\n  query GetJourney($id: ID!) {\n    journey(id: $id, idType: slug) {\n      ...JourneyFields\n    }\n  }\n"): (typeof documents)["\n  query GetJourney($id: ID!) {\n    journey(id: $id, idType: slug) {\n      ...JourneyFields\n    }\n  }\n"];
export function graphql(source: "\n  query GetJourneySlugs {\n    journeys {\n      slug\n    }\n  }\n"): (typeof documents)["\n  query GetJourneySlugs {\n    journeys {\n      slug\n    }\n  }\n"];
export function graphql(source: "\n      query GetJourneys {\n        journeys(where: { featured: true }) {\n          id\n          title\n          slug\n        }\n      }\n    "): (typeof documents)["\n      query GetJourneys {\n        journeys(where: { featured: true }) {\n          id\n          title\n          slug\n        }\n      }\n    "];
export function graphql(source: "\n  mutation JourneyViewEventCreate($input: JourneyViewEventCreateInput!) {\n    journeyViewEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation JourneyViewEventCreate($input: JourneyViewEventCreateInput!) {\n    journeyViewEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation ButtonClickEventCreate($input: ButtonClickEventCreateInput!) {\n    buttonClickEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation ButtonClickEventCreate($input: ButtonClickEventCreateInput!) {\n    buttonClickEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation ChatOpenEventCreate($input: ChatOpenEventCreateInput!) {\n    chatOpenEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation ChatOpenEventCreate($input: ChatOpenEventCreateInput!) {\n    chatOpenEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  \n  fragment ButtonFields on ButtonBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    buttonVariant: variant\n    buttonColor: color\n    size\n    startIconId\n    endIconId\n    action {\n      ...ActionFields\n    }\n  }\n"): (typeof documents)["\n  \n  fragment ButtonFields on ButtonBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    buttonVariant: variant\n    buttonColor: color\n    size\n    startIconId\n    endIconId\n    action {\n      ...ActionFields\n    }\n  }\n"];
export function graphql(source: "\n  fragment CardFields on CardBlock {\n    id\n    parentBlockId\n    parentOrder\n    backgroundColor\n    coverBlockId\n    themeMode\n    themeName\n    fullscreen\n  }\n"): (typeof documents)["\n  fragment CardFields on CardBlock {\n    id\n    parentBlockId\n    parentOrder\n    backgroundColor\n    coverBlockId\n    themeMode\n    themeName\n    fullscreen\n  }\n"];
export function graphql(source: "\n  fragment GridContainerFields on GridContainerBlock {\n    id\n    parentBlockId\n    parentOrder\n    spacing\n    direction\n    justifyContent\n    alignItems\n  }\n"): (typeof documents)["\n  fragment GridContainerFields on GridContainerBlock {\n    id\n    parentBlockId\n    parentOrder\n    spacing\n    direction\n    justifyContent\n    alignItems\n  }\n"];
export function graphql(source: "\n  fragment GridItemFields on GridItemBlock {\n    id\n    parentBlockId\n    parentOrder\n    xl\n    lg\n    sm\n  }\n"): (typeof documents)["\n  fragment GridItemFields on GridItemBlock {\n    id\n    parentBlockId\n    parentOrder\n    xl\n    lg\n    sm\n  }\n"];
export function graphql(source: "\n  fragment IconFields on IconBlock {\n    id\n    parentBlockId\n    parentOrder\n    iconName: name\n    iconSize: size\n    iconColor: color\n  }\n"): (typeof documents)["\n  fragment IconFields on IconBlock {\n    id\n    parentBlockId\n    parentOrder\n    iconName: name\n    iconSize: size\n    iconColor: color\n  }\n"];
export function graphql(source: "\n  fragment ImageFields on ImageBlock {\n    id\n    parentBlockId\n    parentOrder\n    src\n    alt\n    width\n    height\n    blurhash\n  }\n"): (typeof documents)["\n  fragment ImageFields on ImageBlock {\n    id\n    parentBlockId\n    parentOrder\n    src\n    alt\n    width\n    height\n    blurhash\n  }\n"];
export function graphql(source: "\n  \n  fragment RadioOptionFields on RadioOptionBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    action {\n      ...ActionFields\n    }\n  }\n"): (typeof documents)["\n  \n  fragment RadioOptionFields on RadioOptionBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    action {\n      ...ActionFields\n    }\n  }\n"];
export function graphql(source: "\n  mutation RadioQuestionSubmissionEventCreate(\n    $input: RadioQuestionSubmissionEventCreateInput!\n  ) {\n    radioQuestionSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation RadioQuestionSubmissionEventCreate(\n    $input: RadioQuestionSubmissionEventCreateInput!\n  ) {\n    radioQuestionSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  fragment RadioQuestionFields on RadioQuestionBlock {\n    id\n    parentBlockId\n    parentOrder\n  }\n"): (typeof documents)["\n  fragment RadioQuestionFields on RadioQuestionBlock {\n    id\n    parentBlockId\n    parentOrder\n  }\n"];
export function graphql(source: "\n  mutation SignUpSubmissionEventCreate(\n    $input: SignUpSubmissionEventCreateInput!\n  ) {\n    signUpSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation SignUpSubmissionEventCreate(\n    $input: SignUpSubmissionEventCreateInput!\n  ) {\n    signUpSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  \n  fragment SignUpFields on SignUpBlock {\n    id\n    parentBlockId\n    parentOrder\n    submitLabel\n    submitIconId\n    action {\n      ...ActionFields\n    }\n  }\n"): (typeof documents)["\n  \n  fragment SignUpFields on SignUpBlock {\n    id\n    parentBlockId\n    parentOrder\n    submitLabel\n    submitIconId\n    action {\n      ...ActionFields\n    }\n  }\n"];
export function graphql(source: "\n  mutation StepViewEventCreate($input: StepViewEventCreateInput!) {\n    stepViewEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation StepViewEventCreate($input: StepViewEventCreateInput!) {\n    stepViewEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  fragment StepFields on StepBlock {\n    id\n    parentBlockId\n    parentOrder\n    locked\n    nextBlockId\n  }\n"): (typeof documents)["\n  fragment StepFields on StepBlock {\n    id\n    parentBlockId\n    parentOrder\n    locked\n    nextBlockId\n  }\n"];
export function graphql(source: "\n  mutation TextResponseSubmissionEventCreate(\n    $input: TextResponseSubmissionEventCreateInput!\n  ) {\n    textResponseSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation TextResponseSubmissionEventCreate(\n    $input: TextResponseSubmissionEventCreateInput!\n  ) {\n    textResponseSubmissionEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  \n  fragment TextResponseFields on TextResponseBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    hint\n    minRows\n    submitLabel\n    submitIconId\n    action {\n      ...ActionFields\n    }\n  }\n"): (typeof documents)["\n  \n  fragment TextResponseFields on TextResponseBlock {\n    id\n    parentBlockId\n    parentOrder\n    label\n    hint\n    minRows\n    submitLabel\n    submitIconId\n    action {\n      ...ActionFields\n    }\n  }\n"];
export function graphql(source: "\n  fragment TypographyFields on TypographyBlock {\n    id\n    parentBlockId\n    parentOrder\n    align\n    color\n    content\n    variant\n  }\n"): (typeof documents)["\n  fragment TypographyFields on TypographyBlock {\n    id\n    parentBlockId\n    parentOrder\n    align\n    color\n    content\n    variant\n  }\n"];
export function graphql(source: "\n  \n  fragment VideoFields on VideoBlock {\n    id\n    parentBlockId\n    parentOrder\n    muted\n    autoplay\n    startAt\n    endAt\n    posterBlockId\n    fullsize\n    videoId\n    videoVariantLanguageId\n    source\n    title\n    description\n    image\n    duration\n    video {\n      id\n      title(primary: true) {\n        value\n      }\n      image\n      variant {\n        id\n        hls\n      }\n    }\n    action {\n      ...ActionFields\n    }\n  }\n"): (typeof documents)["\n  \n  fragment VideoFields on VideoBlock {\n    id\n    parentBlockId\n    parentOrder\n    muted\n    autoplay\n    startAt\n    endAt\n    posterBlockId\n    fullsize\n    videoId\n    videoVariantLanguageId\n    source\n    title\n    description\n    image\n    duration\n    video {\n      id\n      title(primary: true) {\n        value\n      }\n      image\n      variant {\n        id\n        hls\n      }\n    }\n    action {\n      ...ActionFields\n    }\n  }\n"];
export function graphql(source: "\n  mutation VideoStartEventCreate($input: VideoStartEventCreateInput!) {\n    videoStartEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation VideoStartEventCreate($input: VideoStartEventCreateInput!) {\n    videoStartEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation VideoPlayEventCreate($input: VideoPlayEventCreateInput!) {\n    videoPlayEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation VideoPlayEventCreate($input: VideoPlayEventCreateInput!) {\n    videoPlayEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation VideoPauseEventCreate($input: VideoPauseEventCreateInput!) {\n    videoPauseEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation VideoPauseEventCreate($input: VideoPauseEventCreateInput!) {\n    videoPauseEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation VideoCompleteEventCreate($input: VideoCompleteEventCreateInput!) {\n    videoCompleteEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation VideoCompleteEventCreate($input: VideoCompleteEventCreateInput!) {\n    videoCompleteEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation VideoExpandEventCreate($input: VideoExpandEventCreateInput!) {\n    videoExpandEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation VideoExpandEventCreate($input: VideoExpandEventCreateInput!) {\n    videoExpandEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation VideoCollapseEventCreate($input: VideoCollapseEventCreateInput!) {\n    videoCollapseEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation VideoCollapseEventCreate($input: VideoCollapseEventCreateInput!) {\n    videoCollapseEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  mutation VideoProgressEventCreate($input: VideoProgressEventCreateInput!) {\n    videoProgressEventCreate(input: $input) {\n      id\n    }\n  }\n"): (typeof documents)["\n  mutation VideoProgressEventCreate($input: VideoProgressEventCreateInput!) {\n    videoProgressEventCreate(input: $input) {\n      id\n    }\n  }\n"];
export function graphql(source: "\n  \n  fragment VideoTriggerFields on VideoTriggerBlock {\n    id\n    parentBlockId\n    triggerStart\n    triggerAction: action {\n      ...ActionFields\n    }\n  }\n"): (typeof documents)["\n  \n  fragment VideoTriggerFields on VideoTriggerBlock {\n    id\n    parentBlockId\n    triggerStart\n    triggerAction: action {\n      ...ActionFields\n    }\n  }\n"];
export function graphql(source: "\n  \n  \n  fragment JourneyFields on Journey {\n    id\n    slug\n    title\n    description\n    status\n    language {\n      id\n      bcp47\n      iso3\n      name {\n        value\n        primary\n      }\n    }\n    createdAt\n    publishedAt\n    themeName\n    themeMode\n    seoTitle\n    seoDescription\n    template\n    blocks {\n      ...BlockFields\n    }\n    primaryImageBlock {\n      ...ImageFields\n    }\n    userJourneys {\n      id\n      role\n      user {\n        id\n        firstName\n        lastName\n        imageUrl\n      }\n    }\n  }\n"): (typeof documents)["\n  \n  \n  fragment JourneyFields on Journey {\n    id\n    slug\n    title\n    description\n    status\n    language {\n      id\n      bcp47\n      iso3\n      name {\n        value\n        primary\n      }\n    }\n    createdAt\n    publishedAt\n    themeName\n    themeMode\n    seoTitle\n    seoDescription\n    template\n    blocks {\n      ...BlockFields\n    }\n    primaryImageBlock {\n      ...ImageFields\n    }\n    userJourneys {\n      id\n      role\n      user {\n        id\n        firstName\n        lastName\n        imageUrl\n      }\n    }\n  }\n"];
export function graphql(source: "\n  fragment ActionFields on Action {\n    parentBlockId\n    gtmEventName\n    ... on NavigateToBlockAction {\n      blockId\n    }\n    ... on NavigateToJourneyAction {\n      journey {\n        id\n        slug\n        language {\n          bcp47\n        }\n      }\n    }\n    ... on LinkAction {\n      url\n    }\n  }\n"): (typeof documents)["\n  fragment ActionFields on Action {\n    parentBlockId\n    gtmEventName\n    ... on NavigateToBlockAction {\n      blockId\n    }\n    ... on NavigateToJourneyAction {\n      journey {\n        id\n        slug\n        language {\n          bcp47\n        }\n      }\n    }\n    ... on LinkAction {\n      url\n    }\n  }\n"];
export function graphql(source: "\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  fragment BlockFields on Block {\n    id\n    parentBlockId\n    parentOrder\n    ... on ButtonBlock {\n      ...ButtonFields\n    }\n    ... on CardBlock {\n      ...CardFields\n    }\n    ... on GridContainerBlock {\n      ...GridContainerFields\n    }\n    ... on GridItemBlock {\n      ...GridItemFields\n    }\n    ... on IconBlock {\n      ...IconFields\n    }\n    ... on ImageBlock {\n      ...ImageFields\n    }\n    ... on RadioOptionBlock {\n      ...RadioOptionFields\n    }\n    ... on RadioQuestionBlock {\n      ...RadioQuestionFields\n    }\n    ... on SignUpBlock {\n      ...SignUpFields\n    }\n    ... on StepBlock {\n      ...StepFields\n    }\n    ... on TextResponseBlock {\n      ...TextResponseFields\n    }\n    ... on TypographyBlock {\n      ...TypographyFields\n    }\n    ... on VideoBlock {\n      ...VideoFields\n    }\n    ... on VideoTriggerBlock {\n      ...VideoTriggerFields\n    }\n  }\n"): (typeof documents)["\n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  \n  fragment BlockFields on Block {\n    id\n    parentBlockId\n    parentOrder\n    ... on ButtonBlock {\n      ...ButtonFields\n    }\n    ... on CardBlock {\n      ...CardFields\n    }\n    ... on GridContainerBlock {\n      ...GridContainerFields\n    }\n    ... on GridItemBlock {\n      ...GridItemFields\n    }\n    ... on IconBlock {\n      ...IconFields\n    }\n    ... on ImageBlock {\n      ...ImageFields\n    }\n    ... on RadioOptionBlock {\n      ...RadioOptionFields\n    }\n    ... on RadioQuestionBlock {\n      ...RadioQuestionFields\n    }\n    ... on SignUpBlock {\n      ...SignUpFields\n    }\n    ... on StepBlock {\n      ...StepFields\n    }\n    ... on TextResponseBlock {\n      ...TextResponseFields\n    }\n    ... on TypographyBlock {\n      ...TypographyFields\n    }\n    ... on VideoBlock {\n      ...VideoFields\n    }\n    ... on VideoTriggerBlock {\n      ...VideoTriggerFields\n    }\n  }\n"];

export function graphql(source: string): unknown;
export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;